import type { EntityKind, ModelLayer } from "./canonical-model";

export type ProjectionKey = "product-project" | "organization" | "environment" | "workflow" | "timeline" | "schedule" | "team" | "custom";
export type RepLens = "all" | "chronology" | "generation" | "relevance";
export type ViewSpec = { key: ProjectionKey; label: string; labelKo: string; title: string; breadcrumb: string; focusId: string; levels: string[]; entityKinds: EntityKind[]; relationPredicates?: string[]; xRule: string; yRule: string; layerOrder: ModelLayer[] };

const layers: ModelLayer[] = ["goal", "current", "reference", "observed"];
export const viewSpecs: Record<ProjectionKey, ViewSpec> = {
  "product-project": { key: "product-project", label: "Product · Project", labelKo: "제품·프로젝트", title: "Current operating model", breadcrumb: "PRODUCTS & PROJECTS", focusId: "project-ocp-v0", levels: ["ENTERPRISE", "PRODUCT", "PROJECT", "GOAL"], entityKinds: ["enterprise", "product", "project", "goal"], xRule: "Lateral relations", yRule: "Product / Project hierarchy", layerOrder: layers },
  organization: { key: "organization", label: "Organization", labelKo: "조직", title: "Authority & accountability", breadcrumb: "TEAMS, ROLES & ACTORS", focusId: "team-ocp", levels: ["ENTERPRISE", "TEAM", "ROLE", "ACTOR · AGENT", "DECISION"], entityKinds: ["enterprise", "team", "role", "actor", "agent", "decision"], xRule: "Authority and collaboration", yRule: "Accountability hierarchy", layerOrder: layers },
  environment: { key: "environment", label: "Environment", labelKo: "환경", title: "Signals around the work", breadcrumb: "CONTEXT & ENVIRONMENT", focusId: "context-market", levels: ["CONTEXT", "OBSERVATION", "PRODUCT", "GOAL"], entityKinds: ["observation", "product", "goal", "enterprise"], xRule: "Relevance to focal context", yRule: "Context → response", layerOrder: layers },
  workflow: { key: "workflow", label: "Workflow", labelKo: "업무 흐름", title: "Observation to model update", breadcrumb: "BOUNDED IMPROVEMENT PIPELINE", focusId: "gate-evidence", levels: ["TRIGGER", "OBSERVATION", "DERIVATION", "GATE · DECISION", "OUTCOME"], entityKinds: ["trigger", "observation", "derivation", "gate", "decision", "outcome"], xRule: "Process sequence", yRule: "Gate depth", layerOrder: layers },
  timeline: { key: "timeline", label: "Timeline", labelKo: "연대기", title: "Events and revisions", breadcrumb: "CHRONOLOGY VIEW", focusId: "observation-audio", levels: ["CAPTURE", "DERIVATION", "REVIEW", "DECISION", "REVISION"], entityKinds: ["trigger", "observation", "derivation", "gate", "decision", "outcome"], xRule: "Valid-time sequence", yRule: "Event class", layerOrder: layers },
  schedule: { key: "schedule", label: "Schedule", labelKo: "일정", title: "Commitments and forecast", breadcrumb: "SCHEDULE & MILESTONES", focusId: "goal-operating-map", levels: ["GOAL", "PROJECT", "GATE", "OUTCOME"], entityKinds: ["goal", "project", "gate", "decision", "outcome"], xRule: "Planned valid time", yRule: "Commitment hierarchy", layerOrder: layers },
  team: { key: "team", label: "Team", labelKo: "팀", title: "People, agents & work", breadcrumb: "TEAM OPERATING VIEW", focusId: "team-ocp", levels: ["TEAM", "ROLE", "ACTOR · AGENT", "WORK", "GATE"], entityKinds: ["team", "role", "actor", "agent", "project", "gate", "decision"], xRule: "Responsibility links", yRule: "Team → work", layerOrder: layers },
  custom: { key: "custom", label: "Custom", labelKo: "사용자 정의", title: "Saved semantic projection", breadcrumb: "CUSTOM VIEW SPEC", focusId: "project-ocp-v0", levels: ["SYSTEM", "WORK", "EVIDENCE", "DECISION"], entityKinds: ["enterprise", "product", "project", "goal", "team", "observation", "gate", "decision"], xRule: "Saved ordering rules", yRule: "Saved grouping rules", layerOrder: layers },
};
export const projectionKeys = Object.keys(viewSpecs) as ProjectionKey[];
