/** Real browser acceptance. Local profile; not production account tests. */
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
const publicRoot = path.resolve('public');
const server = createServer(async (request, response) => {
  try {
    const pathname = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    const file = path.resolve(publicRoot, '.' + pathname);
    if (!file.startsWith(publicRoot + path.sep)) { response.writeHead(403); response.end(); return; }
    const data = await readFile(file);
    const mime = file.endsWith('.mjs') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html';
    response.writeHead(200, { 'Content-Type': mime }); response.end(data);
  } catch { response.writeHead(404); response.end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const url = `http://127.0.0.1:${server.address().port}/ocp-studio/browser.html`;
const out = '.studio-evidence/editable';
await mkdir(out, { recursive: true });
const checks = [], errors = [];
const record = name => checks.push({ name, passed: true });
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.waitForFunction(() => !!window.workbench);
  assert.match(await page.locator('#env').innerText(), /편집 가능/);
  const state = () => page.evaluate(() => window.workbench.app.getState().graph);
  const original = '  원문 앞 공백\r\n목표: 기획과 화면의 관계를 확인합니다.\r\n';
  await page.getByRole('button', { name: '＋ 원문', exact: true }).click();
  await page.locator('input[name=title]').fill('검증 원문');
  await page.locator('textarea[name=body]').fill(original);
  await page.getByRole('button', { name: '확인 · 기록', exact: true }).click();
  await page.waitForFunction(() => window.workbench.app.getState().graph.nodes.some(n => n.title === '검증 원문'));
  let graph = await state();
  const raw = graph.nodes.find(n => n.title === '검증 원문');
  assert.equal(raw.status, 'classified-first');
  assert.equal(graph.nodes.some(n => n.decisionId), false);
  record('원문 저장은 승격이나 구현 완료가 아니다');
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForFunction(() => !!window.workbench);
  assert.ok((await state()).nodes.some(n => n.id === raw.id));
  record('원문·ID·변경 기록이 새로고침 후 유지된다');
  await page.evaluate(id => window.workbench.app.inspect(id), raw.id);
  await page.getByRole('button', { name: '2차 분류', exact: true }).click();
  await page.locator('textarea[name=rationale]').fill('실제 기획 요구와 화면의 추적 관계');
  await page.getByRole('button', { name: '확인 · 기록', exact: true }).click();
  await page.waitForFunction(id => window.workbench.app.getState().graph.nodes.find(n => n.id === id)?.status === 'classified', raw.id);
  await page.getByRole('button', { name: '승격 검토', exact: true }).click();
  await page.locator('select[name=parentId]').selectOption('product:ocp');
  await page.locator('input[name=targetTitle]').fill('검증 페이지');
  await page.locator('textarea[name=rationale]').fill('원문과 동작 기준을 확인했습니다.');
  await page.locator('textarea[name=acceptance]').fill('제목과 CTA를 렌더링하고 원문을 추적할 것');
  await page.locator('input[name=approve]').check();
  await page.getByRole('button', { name: '확인 · 기록', exact: true }).click();
  await page.getByRole('button', { name: '승인 적용', exact: true }).waitFor();
  graph = await state();
  assert.equal(graph.nodes.filter(n => n.decisionId).length, 0);
  record('승인된 판정과 실제 구현 계층 적용을 분리한다');
  await page.getByRole('button', { name: '승인 적용', exact: true }).click();
  await page.getByRole('button', { name: '디자인 설계', exact: true }).waitFor();
  const work = (await state()).nodes.find(n => n.title === '검증 페이지' && n.kind === 'page');
  assert.ok(work.decisionId);
  record('승인 적용으로 product 아래 실제 page가 생성된다');
  await page.getByRole('button', { name: '디자인 설계', exact: true }).click();
  await page.locator('input[name=heading]').fill('실행되는 OCP 화면');
  await page.locator('textarea[name=body]').fill('원문 → 판정 → 디자인 → 코드');
  await page.locator('input[name=cta]').fill('자세히 보기');
  await page.getByRole('button', { name: '확인 · 기록', exact: true }).click();
  await page.getByRole('button', { name: '디자인 → 코드', exact: true }).waitFor();
  await page.getByRole('button', { name: '디자인 → 코드', exact: true }).click();
  await page.getByRole('button', { name: '화면 실행', exact: true }).waitFor();
  await page.getByRole('button', { name: '화면 실행', exact: true }).click();
  await page.frameLocator('iframe[title="HTML 실행 화면"]').getByRole('heading', { name: '실행되는 OCP 화면', exact: true }).waitFor();
  assert.equal(await page.frameLocator('iframe[title="HTML 실행 화면"]').getByRole('link', { name: '자세히 보기' }).getAttribute('href'), '#details');
  await page.screenshot({ path: out + '/generated-editor.png' });
  await page.locator('.workbench-dialog [data-dismiss]').click();
  record('디자인에서 실제 HTML을 생성하고 격리 프레임에서 실행한다');
  const code = (await state()).nodes.find(n => n.kind === 'code');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'HTML 내려받기', exact: true }).click();
  const download = await downloadPromise;
  assert.equal(await readFile(await download.path(), 'utf8'), code.body);
  record('HTML 내려받기의 실제 바이트가 저장된 코드와 일치한다');
  await page.evaluate(id => window.workbench.app.inspect(id), raw.id);
  await page.getByRole('button', { name: '새 버전 작성', exact: true }).click();
  await page.locator('.workbench-dialog textarea[name=body]').fill('수정된 기획: 새 버전은 원본과 분리합니다.');
  await page.locator('.workbench-dialog [type=submit]').click();
  await page.waitForFunction(id => window.workbench.app.getState().graph.nodes.find(n => n.id === id)?.sourceAlert, work.id);
  assert.ok((await state()).nodes.find(n => n.id === raw.id).body.includes('원문 앞 공백'));
  record('새 원문 버전은 이전 바이트를 보존하고 기존 구현 재검토를 표시한다');
  const fileChooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: '파일 입력', exact: true }).click();
  await (await fileChooser).setFiles({ name: '실제문서.md', mimeType: 'text/markdown', buffer: Buffer.from('  # 파일 원문\r\n\r\n줄바꿈 유지\r\n') });
  await page.waitForFunction(() => window.workbench.app.getState().graph.nodes.some(n => n.title === '실제문서.md'));
  const file = (await state()).nodes.find(n => n.title === '실제문서.md');
  assert.equal(file.body, '  # 파일 원문\r\n\r\n줄바꿈 유지\r\n');
  record('파일 업로드는 원문 공백·CRLF와 첨부 바이트를 그대로 보존한다');
  await page.getByRole('button', { name: '구름 묶기', exact: true }).click();
  await page.locator('.workbench-dialog input[name=title]').fill('실제 기획 구름');
  await page.locator(`.workbench-dialog input[value="${raw.id}"]`).check();
  await page.locator(`.workbench-dialog input[value="${file.id}"]`).check();
  await page.locator('.workbench-dialog [type=submit]').click();
  await page.waitForFunction(() => window.workbench.app.getState().graph.nodes.some(n => n.kind === 'cloud'));
  graph = await state(); const cloud = graph.nodes.find(n => n.kind === 'cloud');
  assert.equal(graph.edges.filter(e => e.from === cloud.id && e.predicate === 'CONTAINS').length, 2);
  record('구름은 복제 대신 원문 ID 두 개를 직접 포함한다');
  const exportPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'BU 백업', exact: true }).click();
  const exported = await exportPromise;
  const bundle = JSON.parse(await readFile(await exported.path(), 'utf8'));
  assert.ok(bundle.objects.some(o => o.key.startsWith('attachment/')));
  assert.ok(bundle.objects.some(o => o.key.startsWith('events/')));
  const fresh = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const mobile = await fresh.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(url, { waitUntil: 'networkidle' });
  await mobile.waitForFunction(() => !!window.workbench);
  await mobile.getByRole('button', { name: '구조 메뉴', exact: true }).click();
  await mobile.getByRole('button', { name: '가져오기', exact: true }).click();
  await mobile.locator('.workbench-dialog input[type=file]').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(bundle)) });
  await mobile.locator('.workbench-dialog input[name=confirm]').check();
  await mobile.locator('.workbench-dialog [type=submit]').click();
  await mobile.waitForFunction(id => window.workbench.app.getState().graph.nodes.some(n => n.id === id), cloud.id);
  await mobile.reload({ waitUntil: 'networkidle' }); await mobile.waitForFunction(() => !!window.workbench);
  assert.ok(await mobile.evaluate(id => window.workbench.app.getState().graph.nodes.some(n => n.id === id), cloud.id));
  record('모바일 새 프로필에서 백업을 복원하고 재시작해도 원문과 구름을 보존한다');
  await mobile.screenshot({ path: out + '/mobile-workspace.png' });
  const other = await context.newPage(); await other.goto(url, { waitUntil: 'networkidle' }); await other.waitForFunction(() => !!window.workbench);
  const revision = (await state()).revision;
  const concurrent = await Promise.all([page, other].map((p, i) => p.evaluate(async ({ revision, i }) => {
    try { await window.workbench.store.command({ id: 'concurrent-command-' + i, expectedRevision: revision, type: 'capture', payload: { title: 'Concurrent ' + i, body: 'CAS check' } }); return 'saved'; }
    catch (error) { return error.code; }
  }, { revision, i })));
  assert.equal(concurrent.filter(x => x === 'saved').length, 1);
  record('두 탭의 동시 변경에서 한 건만 저장하며 오래된 버전을 덮어쓰지 않는다');
  // Use the ordinary close control: the inspector intentionally covers part of the canvas.
  if (await page.locator('[data-action=close-panel]').isVisible()) {
    await page.locator('[data-action=close-panel]').click();
  }
  await page.locator('.stage').click({ position: { x: 500, y: 250 } });
  await page.keyboard.press('3');
  await page.waitForFunction(() => document.querySelector('[data-action=journey]').classList.contains('active'));
  record('실제 브라우저의 숫자 3 단축키로 사용자 대칭 여정을 전환한다');
  await page.locator('[data-action=pipeline]').click(); await page.locator('[data-action=fit]').click();
  await page.screenshot({ path: out + '/editable-workspace.png' });
  assert.equal(errors.length, 0, errors.join('\n'));
  record('브라우저 예외 0건');
  await writeFile(out + '/report.json', JSON.stringify({ scope: 'actual browser UI + IndexedDB; no cloud or production identity', checks, errors }, null, 2));
  console.log(JSON.stringify({ passed: checks.length, scope: 'editable browser workspace' }));
  await fresh.close(); await context.close();
} catch (error) {
  await writeFile(out + '/report.json', JSON.stringify({ checks, errors, failure: String(error) }, null, 2));
  throw error;
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
